export const en={
    translation:{
        "hi":"Hi,",
        "I'm":"I'm",
        "I'm a":"I'm a",
        "FrontEnd Developer":"FrontEnd Developer",
        "Lifelong Learner":"Lifelong Learner",
        "Team Player":"Team Player",
        "Human":"Human",
        "What I use":"What I use",
        "Do you want this at your app?":"Do you want this at your app?",
        'Daily Work Hours':'Daily Work Hours',
        'Monday':'Monday',
        'Tuesday':'Tuesday',
        'Wednesday':'Wednesday',
        'Thursday':'Thursday',
        "Friday":"Friday",
        'Saturday':'Saturday',
        'Sunday':'Sunday',
        'Hour':'Hour',
        'Activity Hours':'Activity Hours',
        'Code':'Code',
        'Eat':'Eat',
        'Sleep':'Sleep',
        'Sport':'Sport',
        'Fun':'Fun',
        'Learn':'Learn',
        'Success/Boredom Chart':'Success/Boredom Chart',
        'January':'January',
        'February':'February',
        'March':'March',
        'April':'April',
        'May':'May',
        'June':'June',
        'July':'July',
        'Success':'Success',
        'Boredom':'Boredom',
        'Technologies':'Technologies',
        'Qualifications':'Qualifications',
        'Communication Skills':'Communication Skills',
        'Team Work':'Team Work',
        'Good Manners':'Good Manners',
        'Curiosity':'Curiosity',
        'Passion':'Passion',
        'Result Orientation':'Result Orientation',
        "Home":"Home",
        "Charts":"Charts"
    }

};
export const tr={
    translation:{
        "hi":"Merhaba,",
        "I'm":"Ben",
        "I'm a":"Ben bir",
        "FrontEnd Developer":"FrontEnd Developerım",
        "Lifelong Learner":"Öğrenme Meraklısıyım",
        "Team Player":"Takım Oyuncusuyum",
        "Human":"İnsanım",
        "What I use":"Hangi Teknolojileri Kullanıyorum",
        "Do you want this at your app?":"Uygulamanızda bunun da olmasını ister misiniz?",
        'Daily Work Hours':'Günlük Çalışma Saatleri',
        'Monday':'Pazartesi',
        'Tuesday':'Salı',
        'Wednesday':'Çarşamba',
        'Thursday':'Perşembe',
        "Friday":"Cuma",
        'Saturday':'Cumartesi',
        'Sunday':'Pazar',
        'Hour':'Saat',
        'Activity Hours':'Aktivite Saatleri',
        'Code':'Kodlama',
        'Eat':'Yemek',
        'Sleep':'Uyku',
        'Sport':'Spor',
        'Fun':'Eğlence',
        'Learn':'Öğrenme',
        'Success/Boredom Chart':'Başarı/Bıkkınlık Grafiği',
        'January':'Ocak',
        'February':'Şubat',
        'March':'Mart',
        'April':'Nisan',
        'May':'Mayıs',
        'June':'Haziran',
        'July':'Temmuz',
        'Success':'Başarı',
        'Boredom':'Bıkkınlık',
        'Technologies':'Teknolojiler',
        'Qualifications':'Niteliklerim',
        'Communication Skills':'İletişim Becerisi',
        'Team Work':'Takım Çalışması',
        'Good Manners':'Pozitif Kişilik',
        'Curiosity':'Merak',
        'Passion':'Hırs',
        'Result Orientation':'Sonuç Odaklı Çalışma',
        "Home":"Anasayfa",
        "Charts":"Grafikler"
    }

};