export const en = {
  translation: {
    "hi": "Hi, I'm",
    "I'm": "I'm",
    "I'm a": "I'm a",
    "FrontEnd Developer": "Frontend Developer",
    "Lifelong Learner": "Lifelong Learner",
    "Team Player": "Team Player",
    "Human": "Human",
    "view_projects": "View Projects",
    "download_cv": "Download CV",
    "What I use": "Tech Stack",
    "Do you want this in your app?": "Enhanced with Technology.",
    "Home": "Home",
    "About": "About",
    "Technologies": "Technologies",
    "Projects": "Projects",
    "Charts": "Charts",
    "MyProjects": "My Projects",
    "about_headline": "Developer by trade,\nperfectionist by nature.",
    "about_bio_1": "I'm a Frontend Developer specializing in Next.js, React and modern JavaScript. I craft fast, accessible, and visually polished web experiences.",
    "about_bio_2": "My work sits at the intersection of engineering and design — I care as much about clean, maintainable code as pixel-perfect interfaces.",
    "years_exp": "Years Exp.",
    "projects_built": "Projects",
    "live_apps": "Live Apps",
    "Contact": "Contact",
    "contact_headline": "Let's Build Something.",
    "contact_sub": "Open to new opportunities, collaborations, and interesting projects. My inbox is always open.",
    "send_email": "Copy Email",
    "copied": "Copied!",
    "service_01_title": "UI Development",
    "service_01_desc": "Pixel-perfect, responsive React interfaces with smooth animations and accessible markup.",
    "service_02_title": "State Architecture",
    "service_02_desc": "Scalable state management with Redux Toolkit, Context API, and React Query.",
    "service_03_title": "Performance",
    "service_03_desc": "Optimized Core Web Vitals, lazy loading, code splitting, and minimal bundle sizes.",
    "switch_view_hint": "Switch view",
    "robot_title": "Interactive Robot",
    "robot_desc": "A real-time 3D scene I embedded directly in the browser — showcasing my ability to integrate immersive WebGL experiences into production-ready interfaces.",
    "robot_tech": "Spline · WebGL",
    "phone_model_title": "3D Phone Model",
    "phone_model_desc": "A custom 3D model I built and animated with React Three Fiber & Three.js — demonstrating my ability to craft interactive, physics-aware web experiences from scratch.",
    "phone_model_tech": "React Three Fiber · Three.js",
    "charts_headline": "By the numbers.",
    "phone_sub_3d": "Interactive 3D models built with Three.js & React Three Fiber.",
    "project_food_desc": "A full-featured React food ordering application with cart management, product filtering, and fully responsive layout.",
    "project_dashboard_desc": "A comprehensive bank admin dashboard with analytics charts, data tables, and multi-level user management.",
    "project_shop_desc": "A modern e-commerce shopping application with product filtering, cart functionality, and smooth checkout flow.",
    "project_arch_desc": "A professional architecture firm website with project showcases, team section, and optimized performance.",
    "project_live": "Live",
    "project_code": "Code",
    "project_view_live": "View Live",
    "project_source_code": "Source Code",
    "theme_label": "Theme",
    "lang_label": "Language",
    "music_label": "Music",
    "Daily Work Hours": "Daily Work Hours",
    "Monday": "Monday",
    "Tuesday": "Tuesday",
    "Wednesday": "Wednesday",
    "Thursday": "Thursday",
    "Friday": "Friday",
    "Saturday": "Saturday",
    "Sunday": "Sunday",
    "Hour": "Hour",
    "Activity Hours": "Activity Hours",
    "Code": "Code",
    "Eat": "Eat",
    "Sleep": "Sleep",
    "Sport": "Sport",
    "Fun": "Fun",
    "Learn": "Learn",
    "Success/Boredom Chart": "Skills vs. Bugs",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "Success": "Skill Level",
    "Boredom": "Bug Count",
    "Qualifications": "Qualifications",
    "Communication Skills": "Communication Skills",
    "Team Work": "Team Work",
    "Good Manners": "Good Manners",
    "Curiosity": "Curiosity",
    "Passion": "Passion",
    "Result Orientation": "Result Orientation"
  }
};

export const de = {
  translation: {
    "hi": "Hallo, ich bin",
    "I'm": "Ich bin",
    "I'm a": "Ich bin ein",
    "FrontEnd Developer": "Frontend-Entwickler",
    "Lifelong Learner": "Lebenslanger Lerner",
    "Team Player": "Teamplayer",
    "Human": "Mensch",
    "view_projects": "Projekte ansehen",
    "download_cv": "Lebenslauf herunterladen",
    "What I use": "Technologie-Stack",
    "Do you want this in your app?": "Mit Technologie aufgewertet.",
    "Home": "Startseite",
    "About": "Über mich",
    "Technologies": "Technologien",
    "Projects": "Projekte",
    "Charts": "Diagramme",
    "MyProjects": "Meine Projekte",
    "about_headline": "Entwickler von Beruf,\nPerfektionist von Natur.",
    "about_bio_1": "Ich bin ein Frontend-Entwickler, spezialisiert auf Next.js, React und modernes JavaScript. Ich entwickle schnelle, zugängliche und visuell ansprechende Web-Erlebnisse.",
    "about_bio_2": "Meine Arbeit liegt an der Schnittstelle von Technik und Design — ich lege genauso viel Wert auf sauberen, wartbaren Code wie auf pixelgenaue Benutzeroberflächen.",
    "years_exp": "Jahre Erfahrung",
    "projects_built": "Projekte",
    "live_apps": "Live-Apps",
    "Contact": "Kontakt",
    "contact_headline": "Lass uns etwas aufbauen.",
    "contact_sub": "Offen für neue Möglichkeiten, Kooperationen und interessante Projekte. Mein Posteingang ist immer offen.",
    "send_email": "E-Mail kopieren",
    "copied": "Kopiert!",
    "service_01_title": "UI-Entwicklung",
    "service_01_desc": "Pixelgenaue, responsive React-Oberflächen mit flüssigen Animationen und barrierefreiem Markup.",
    "service_02_title": "State-Architektur",
    "service_02_desc": "Skalierbares State-Management mit Redux Toolkit, Context API und React Query.",
    "service_03_title": "Performance",
    "service_03_desc": "Optimierte Core Web Vitals, Lazy Loading, Code Splitting und minimale Bundle-Größen.",
    "switch_view_hint": "Ansicht wechseln",
    "robot_title": "Interaktiver Roboter",
    "robot_desc": "Eine Echtzeit-3D-Szene, die ich direkt im Browser eingebettet habe — zeigt meine Fähigkeit, immersive WebGL-Erlebnisse in produktionsreife Interfaces zu integrieren.",
    "robot_tech": "Spline · WebGL",
    "phone_model_title": "3D-Telefonmodell",
    "phone_model_desc": "Ein eigenes 3D-Modell, das ich mit React Three Fiber & Three.js gebaut und animiert habe — ein Beweis meiner Fähigkeit, interaktive Web-Erlebnisse von Grund auf zu entwickeln.",
    "phone_model_tech": "React Three Fiber · Three.js",
    "charts_headline": "In Zahlen.",
    "phone_sub_3d": "Interaktive 3D-Modelle mit Three.js & React Three Fiber.",
    "project_food_desc": "Eine voll ausgestattete React-Lebensmittelbestellanwendung mit Warenkorbverwaltung, Produktfilterung und vollständig responsivem Layout.",
    "project_dashboard_desc": "Ein umfassendes Bank-Admin-Dashboard mit Analysediagrammen, Datentabellen und mehrstufiger Benutzerverwaltung.",
    "project_shop_desc": "Eine moderne E-Commerce-Anwendung mit Produktfilterung, Warenkorb-Funktion und reibungslosem Checkout-Ablauf.",
    "project_arch_desc": "Eine professionelle Website eines Architekturbüros mit Projektpräsentationen, Teambereich und optimierter Performance.",
    "project_live": "Live",
    "project_code": "Code",
    "project_view_live": "Live ansehen",
    "project_source_code": "Quellcode",
    "theme_label": "Design",
    "lang_label": "Sprache",
    "music_label": "Musik",
    "Daily Work Hours": "Tägliche Arbeitsstunden",
    "Monday": "Montag",
    "Tuesday": "Dienstag",
    "Wednesday": "Mittwoch",
    "Thursday": "Donnerstag",
    "Friday": "Freitag",
    "Saturday": "Samstag",
    "Sunday": "Sonntag",
    "Hour": "Stunde",
    "Activity Hours": "Aktivitätsstunden",
    "Code": "Programmieren",
    "Eat": "Essen",
    "Sleep": "Schlafen",
    "Sport": "Sport",
    "Fun": "Spaß",
    "Learn": "Lernen",
    "Success/Boredom Chart": "Skills vs. Bugs",
    "January": "Januar",
    "February": "Februar",
    "March": "März",
    "April": "April",
    "May": "Mai",
    "June": "Juni",
    "July": "Juli",
    "Success": "Skill-Level",
    "Boredom": "Bug-Anzahl",
    "Qualifications": "Qualifikationen",
    "Communication Skills": "Kommunikationsfähigkeit",
    "Team Work": "Teamarbeit",
    "Good Manners": "Positive Persönlichkeit",
    "Curiosity": "Neugier",
    "Passion": "Leidenschaft",
    "Result Orientation": "Ergebnisorientierung"
  }
};

export const tr = {
  translation: {
    "hi": "Merhaba, ben",
    "I'm": "Ben",
    "I'm a": "Ben bir",
    "FrontEnd Developer": "Frontend Developerım",
    "Lifelong Learner": "Öğrenme Meraklısıyım",
    "Team Player": "Takım Oyuncusuyum",
    "Human": "İnsanım",
    "view_projects": "Projelerim",
    "download_cv": "CV İndir",
    "What I use": "Kullandığım Teknolojiler",
    "Do you want this in your app?": "Teknolojiyle Güçlendirildi.",
    "Home": "Anasayfa",
    "About": "Hakkımda",
    "Technologies": "Teknolojiler",
    "Projects": "Projelerim",
    "Charts": "Grafikler",
    "MyProjects": "Projelerim",
    "about_headline": "Mesleğim geliştirici,\ndoğamsa mükemmeliyetçi.",
    "about_bio_1": "Next.js, React ve modern JavaScript üzerine uzmanlaşmış bir Frontend Developer'ım. Hızlı, erişilebilir ve görsel açıdan özenli web deneyimleri inşa ediyorum.",
    "about_bio_2": "Çalışmam mühendislik ve tasarımın kesişim noktasında duruyor — temiz, sürdürülebilir kodla piksel mükemmelliğine aynı özeni gösteriyorum.",
    "years_exp": "Yıl Deneyim",
    "projects_built": "Proje",
    "live_apps": "Canlı Uygulama",
    "Contact": "İletişim",
    "contact_headline": "Birlikte Üretelim.",
    "contact_sub": "Yeni fırsatlara, iş birliklerine ve ilginç projelere açığım. Mesajınızı bekliyorum.",
    "send_email": "E-posta Kopyala",
    "copied": "Kopyalandı!",
    "service_01_title": "Arayüz Geliştirme",
    "service_01_desc": "Sorunsuz animasyonlar ve erişilebilir markup ile piksel mükemmelliğinde, duyarlı React arayüzleri.",
    "service_02_title": "State Mimarisi",
    "service_02_desc": "Redux Toolkit, Context API ve React Query ile ölçeklenebilir state yönetimi.",
    "service_03_title": "Performans",
    "service_03_desc": "Optimize edilmiş Core Web Vitals, lazy loading, code splitting ve minimal bundle boyutları.",
    "switch_view_hint": "Görünümü değiştir",
    "robot_title": "İnteraktif Robot",
    "robot_desc": "Doğrudan tarayıcıya gömdüğüm gerçek zamanlı bir 3D sahne — WebGL deneyimlerini üretim kalitesindeki arayüzlere entegre etme yeteneğimi ortaya koyuyor.",
    "robot_tech": "Spline · WebGL",
    "phone_model_title": "3D Telefon Modeli",
    "phone_model_desc": "React Three Fiber & Three.js ile sıfırdan geliştirip animasyonladığım özel bir 3D model — gerçek dünyanın dokusunu web'e taşıma yeteneğimin göstergesi.",
    "phone_model_tech": "React Three Fiber · Three.js",
    "charts_headline": "Sayılarla.",
    "phone_sub_3d": "Three.js ve React Three Fiber ile interaktif 3D modeller.",
    "project_food_desc": "Sepet yönetimi, ürün filtreleme ve tam duyarlı tasarım içeren kapsamlı bir React yemek sipariş uygulaması.",
    "project_dashboard_desc": "Analiz grafikleri, veri tabloları ve çok seviyeli kullanıcı yönetimiyle donatılmış kapsamlı bir banka admin paneli.",
    "project_shop_desc": "Ürün filtreleme, sepet işlevselliği ve sorunsuz ödeme akışına sahip modern bir e-ticaret alışveriş uygulaması.",
    "project_arch_desc": "Proje vitrini, ekip bölümü ve optimize edilmiş performanslı profesyonel bir mimarlık firması web sitesi.",
    "project_live": "Canlı",
    "project_code": "Kod",
    "project_view_live": "Canlıya Git",
    "project_source_code": "Kaynak Kod",
    "theme_label": "Tema",
    "lang_label": "Dil",
    "music_label": "Müzik",
    "Daily Work Hours": "Günlük Çalışma Saatleri",
    "Monday": "Pazartesi",
    "Tuesday": "Salı",
    "Wednesday": "Çarşamba",
    "Thursday": "Perşembe",
    "Friday": "Cuma",
    "Saturday": "Cumartesi",
    "Sunday": "Pazar",
    "Hour": "Saat",
    "Activity Hours": "Aktivite Saatleri",
    "Code": "Kodlama",
    "Eat": "Yemek",
    "Sleep": "Uyku",
    "Sport": "Spor",
    "Fun": "Eğlence",
    "Learn": "Öğrenme",
    "Success/Boredom Chart": "Beceri vs. Bug",
    "January": "Ocak",
    "February": "Şubat",
    "March": "Mart",
    "April": "Nisan",
    "May": "Mayıs",
    "June": "Haziran",
    "July": "Temmuz",
    "Success": "Beceri Seviyesi",
    "Boredom": "Bug Sayısı",
    "Qualifications": "Niteliklerim",
    "Communication Skills": "İletişim Becerisi",
    "Team Work": "Takım Çalışması",
    "Good Manners": "Pozitif Kişilik",
    "Curiosity": "Merak",
    "Passion": "Hırs",
    "Result Orientation": "Sonuç Odaklı"
  }
};
